version: '3.4'

services:

  db:
    image: mariadb:10.2.40-bionic
    ports:
      - 7601:3306
    environment:
      MYSQL_ROOT_PASSWORD: super_ultra_secreto
    volumes:
      - db:/var/lib/mysql
      - ./database/:/docker-entrypoint-initdb.d/

  frontend:
    image: node:16.6.2-alpine3.14
    working_dir: /app
    command: sh -c 'npm install && npm run serve'
    ports:
      - 7602:8080
    volumes:
      - ./frontend/:/app
      - node_modules:/app/node_modules

  backend:
    image: golang:1.16.7-alpine
    working_dir: /app
    command: go run .
    ports: 
      - 7603:8080
    volumes: 
      - ./backend:/app

volumes:
  db:
  node_modules:
